import json

with open('scripts/build_dashboard.py', 'r', encoding='utf-8') as f:
    content = f.read()

start_marker = 'return `<!DOCTYPE html>'
end_marker = '</html>'
start_idx = content.find(start_marker)
end_idx = content.find(end_marker, start_idx)

if start_idx != -1 and end_idx != -1:
    html_raw = '<!DOCTYPE html>' + content[start_idx + len(start_marker):end_idx + len('</html>')]
    
    # Replace ${port} placeholder with __PORT__ for clean substitution
    html_raw = html_raw.replace('\\${', '${').replace('\\`', '`')
    html_raw = html_raw.replace('${port}', '__PORT__')
    
    ts_code = f'''// Generated by scripts/generate_html.py — Composio-grade Kater Dev Tools Integration Hub
const RAW_HTML = {json.dumps(html_raw)};

export function getDashboardHtml(port: number): string {{
  return RAW_HTML.split('__PORT__').join(String(port));
}}
'''
    with open('src/dashboardHtml.ts', 'w', encoding='utf-8') as f_out:
        f_out.write(ts_code)
    print('Generated src/dashboardHtml.ts successfully, size:', len(ts_code))
else:
    print('Failed to find markers', start_idx, end_idx)

