import { McpServerDoc } from './types.js';

export const INITIAL_SERVERS: McpServerDoc[] = [
  {
    name: 'kater',
    description: 'Native Kater gateway: profiles, doctor, chains, config, adapters.',
    transport: 'native',
    risk: 'low',
    profiles: ['core', 'dev', 'ops', 'full'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 1,
    homepage: 'https://github.com/GroepOnline/kater-dev-tools',
  },
  {
    name: 'github',
    description: 'GitHub PR, issue, code search, and CI operations.',
    transport: 'stdio',
    risk: 'high',
    profiles: ['ops', 'code', 'dev', 'full'],
    enabled: true,
    env_required: ['GITHUB_PERSONAL_ACCESS_TOKEN'],
    env_configured: true,
    context_cost: 4,
    homepage: 'https://github.com/modelcontextprotocol/servers',
    mcp: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-github@2025.4.8'],
      env_template: { GITHUB_PERSONAL_ACCESS_TOKEN: '${GITHUB_PERSONAL_ACCESS_TOKEN}' },
    },
  },
  {
    name: 'gitlab',
    description: 'GitLab merge requests, issues, and pipelines.',
    transport: 'stdio',
    risk: 'high',
    profiles: ['ops', 'code', 'dev'],
    enabled: false,
    env_required: ['GITLAB_PERSONAL_ACCESS_TOKEN'],
    env_configured: false,
    context_cost: 4,
    homepage: 'https://github.com/modelcontextprotocol/servers',
    mcp: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-gitlab@2025.4.25'],
      env_template: { GITLAB_PERSONAL_ACCESS_TOKEN: '${GITLAB_PERSONAL_ACCESS_TOKEN}' },
    },
  },
  {
    name: 'linear',
    description: 'Linear issue and project operations.',
    transport: 'http',
    risk: 'medium',
    profiles: ['ops', 'dev'],
    enabled: true,
    env_required: ['LINEAR_API_KEY'],
    env_configured: true,
    context_cost: 3,
    homepage: 'https://linear.app',
    mcp: {
      url: 'https://mcp.linear.app/mcp',
      headers_template: { Authorization: 'Bearer ${LINEAR_API_KEY}' },
    },
  },
  {
    name: 'sentry',
    description: 'Sentry issue, release, and observability tools.',
    transport: 'http',
    risk: 'medium',
    profiles: ['ops', 'dev'],
    enabled: true,
    env_required: ['SENTRY_AUTH_TOKEN'],
    env_configured: true,
    context_cost: 3,
    homepage: 'https://sentry.io',
    mcp: {
      url: 'https://mcp.sentry.dev/sse',
      headers_template: { Authorization: 'Bearer ${SENTRY_AUTH_TOKEN}' },
    },
  },
  {
    name: 'exa',
    description: 'Exa web search and page fetch tools.',
    transport: 'http',
    risk: 'medium',
    profiles: ['research', 'web', 'dev'],
    enabled: true,
    env_required: ['EXA_API_KEY'],
    env_configured: true,
    context_cost: 3,
    homepage: 'https://exa.ai',
    mcp: {
      url: 'https://mcp.exa.ai/sse',
      env_template: { EXA_API_KEY: '${EXA_API_KEY}' },
    },
  },
  {
    name: 'firecrawl',
    description: 'Firecrawl web search, scrape, crawl, and extraction.',
    transport: 'stdio',
    risk: 'medium',
    profiles: ['research', 'web'],
    enabled: false,
    env_required: ['FIRECRAWL_API_KEY'],
    env_configured: false,
    context_cost: 5,
    homepage: 'https://firecrawl.dev',
    mcp: {
      command: 'npx',
      args: ['-y', 'firecrawl-mcp@3.22.1'],
      env_template: { FIRECRAWL_API_KEY: '${FIRECRAWL_API_KEY}' },
    },
  },
  {
    name: 'huggingface',
    description: 'Hugging Face models, datasets, papers, and spaces.',
    transport: 'http',
    risk: 'medium',
    profiles: ['research', 'cloud'],
    enabled: true,
    env_required: ['HF_TOKEN'],
    env_configured: true,
    context_cost: 5,
    homepage: 'https://huggingface.co',
    mcp: {
      url: 'https://huggingface.co/mcp/sse',
      env_template: { HF_TOKEN: '${HF_TOKEN}' },
    },
  },
  {
    name: 'sanity',
    description: 'Sanity CMS content management and query tools.',
    transport: 'http',
    risk: 'high',
    profiles: ['content'],
    enabled: false,
    env_required: ['SANITY_API_TOKEN'],
    env_configured: false,
    context_cost: 3,
    homepage: 'https://sanity.io',
    mcp: {
      url: 'https://mcp.sanity.io/sse',
      env_template: { SANITY_API_TOKEN: '${SANITY_API_TOKEN}' },
    },
  },
  {
    name: 'cloudflare',
    description: 'Cloudflare Workers, R2, D1, KV, Durable Objects, and DNS tools.',
    transport: 'http',
    risk: 'high',
    profiles: ['cloud', 'ops', 'full'],
    enabled: true,
    env_required: ['CLOUDFLARE_ACCOUNT_ID', 'CLOUDFLARE_API_TOKEN'],
    env_configured: true,
    context_cost: 4,
    homepage: 'https://developers.cloudflare.com',
    mcp: {
      url: 'https://mcp.cloudflare.com/mcp',
      headers_template: { Authorization: 'Bearer ${CLOUDFLARE_API_TOKEN}' },
    },
  },
  {
    name: 'upstash',
    description: 'Upstash Redis, QStash, Workflow, and Box management.',
    transport: 'stdio',
    risk: 'high',
    profiles: ['cloud', 'ops'],
    enabled: false,
    env_required: ['UPSTASH_EMAIL', 'UPSTASH_API_KEY'],
    env_configured: false,
    context_cost: 3,
    homepage: 'https://upstash.com',
    mcp: {
      command: 'npx',
      args: ['-y', '@upstash/mcp-server@0.2.3'],
      env_template: {
        UPSTASH_EMAIL: '${UPSTASH_EMAIL}',
        UPSTASH_API_KEY: '${UPSTASH_API_KEY}',
      },
    },
  },
  {
    name: 'browser',
    description: 'Playwright browser automation and scraping tools.',
    transport: 'stdio',
    risk: 'medium',
    profiles: ['web', 'dev', 'browser', 'full'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 4,
    homepage: 'https://playwright.dev',
    mcp: {
      command: 'npx',
      args: ['-y', '@playwright/mcp@0.0.76'],
    },
  },
  {
    name: 'resend',
    description: 'Resend email, contacts, broadcasts, and templates.',
    transport: 'stdio',
    risk: 'high',
    profiles: ['email', 'content'],
    enabled: false,
    env_required: ['RESEND_API_KEY'],
    env_configured: false,
    context_cost: 5,
    homepage: 'https://resend.com',
    mcp: {
      command: 'npx',
      args: ['-y', 'resend-mcp@2.9.0'],
      env_template: { RESEND_API_KEY: '${RESEND_API_KEY}' },
    },
  },
  {
    name: 'slack',
    description: 'Slack workspace via Slack-hosted MCP with OAuth authorization.',
    transport: 'http',
    risk: 'high',
    profiles: ['email', 'ops'],
    enabled: false,
    env_required: ['SLACK_ACCESS_TOKEN'],
    env_configured: false,
    context_cost: 4,
    homepage: 'https://mcp.slack.com/mcp',
    oauth: {
      provider: 'slack',
      authorize_url: 'https://slack.com/oauth/v2_user/authorize',
      token_url: 'https://slack.com/api/oauth.v2.user.access',
      client_id_env: 'SLACK_MCP_CLIENT_ID',
      client_secret_env: 'SLACK_MCP_CLIENT_SECRET',
      pkce: true,
      token_env: 'SLACK_ACCESS_TOKEN',
      refresh_env: 'SLACK_REFRESH_TOKEN',
      resource: 'https://mcp.slack.com/mcp',
    },
    mcp: {
      url: 'https://mcp.slack.com/mcp',
      headers_template: { Authorization: 'Bearer ${SLACK_ACCESS_TOKEN}' },
    },
  },
  {
    name: 'quiverai',
    description: 'QuiverAI SVG generation and asset tools.',
    transport: 'http',
    risk: 'medium',
    profiles: ['image', 'content'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 3,
    homepage: 'https://quiver.ai',
    mcp: {
      url: 'https://mcp.quiver.ai/sse',
    },
  },
  {
    name: 'figma',
    description: 'Figma design file access and dev-mode tools.',
    transport: 'stdio',
    risk: 'medium',
    profiles: ['image', 'content', 'dev'],
    enabled: false,
    env_required: ['FIGMA_API_KEY'],
    env_configured: false,
    context_cost: 3,
    homepage: 'https://figma.com',
    mcp: {
      command: 'npx',
      args: ['-y', 'figma-developer-mcp@0.13.2'],
      env_template: { FIGMA_API_KEY: '${FIGMA_API_KEY}' },
    },
  },
  {
    name: 'postgres',
    description: 'PostgreSQL query and schema tools.',
    transport: 'stdio',
    risk: 'high',
    profiles: ['cloud', 'ops', 'data'],
    enabled: false,
    env_required: ['DATABASE_URL'],
    env_configured: false,
    context_cost: 3,
    homepage: 'https://postgresql.org',
    mcp: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-postgres@0.6.2'],
      env_template: { DATABASE_URL: '${DATABASE_URL}' },
    },
  },
  {
    name: 'sqlite',
    description: 'SQLite local database query tools.',
    transport: 'stdio',
    risk: 'medium',
    profiles: ['code', 'data', 'dev'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 2,
    homepage: 'https://sqlite.org',
    mcp: {
      command: 'npx',
      args: ['-y', 'mcp-server-sqlite-npx@0.8.0'],
    },
  },
  {
    name: 'filesystem',
    description: 'Local filesystem read/write/search tools.',
    transport: 'stdio',
    risk: 'medium',
    profiles: ['code', 'dev', 'core'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 2,
    homepage: 'https://github.com/modelcontextprotocol/servers',
    mcp: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-filesystem@2026.1.14'],
    },
  },
  {
    name: 'brave-search',
    description: 'Brave Search web search tools.',
    transport: 'stdio',
    risk: 'low',
    profiles: ['research', 'web', 'dev'],
    enabled: true,
    env_required: ['BRAVE_API_KEY'],
    env_configured: true,
    context_cost: 2,
    homepage: 'https://brave.com/search',
    mcp: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-brave-search@0.6.2'],
      env_template: { BRAVE_API_KEY: '${BRAVE_API_KEY}' },
    },
  },
  {
    name: 'sequential-thinking',
    description: 'Sequential reasoning and thought-chain tools.',
    transport: 'stdio',
    risk: 'low',
    profiles: ['reasoning', 'research', 'core', 'dev'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 1,
    homepage: 'https://github.com/modelcontextprotocol/servers',
    mcp: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-sequential-thinking@2025.12.18'],
    },
  },
  {
    name: 'memory',
    description: 'Persistent knowledge graph and memory tools.',
    transport: 'stdio',
    risk: 'low',
    profiles: ['reasoning', 'core', 'dev'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 1,
    homepage: 'https://github.com/modelcontextprotocol/servers',
    mcp: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-memory@2026.1.26'],
    },
  },
  {
    name: 'context7',
    description: 'Context7: up-to-date docs for any library or framework.',
    transport: 'stdio',
    risk: 'low',
    profiles: ['code', 'research', 'docs', 'dev'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 2,
    homepage: 'https://context7.com',
    mcp: {
      command: 'npx',
      args: ['-y', '@upstash/context7-mcp@3.2.2'],
    },
  },
  {
    name: 'deepwiki',
    description: 'DeepWiki: AI-powered repository documentation and Q&A.',
    transport: 'stdio',
    risk: 'low',
    profiles: ['code', 'research', 'docs'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 2,
    homepage: 'https://deepwiki.com',
    mcp: {
      command: 'npx',
      args: ['-y', 'deepwiki-mcp@0.0.6'],
    },
  },
  {
    name: 'notion',
    description: 'Notion pages, databases, and workspace search.',
    transport: 'stdio',
    risk: 'high',
    profiles: ['content', 'ops'],
    enabled: false,
    env_required: ['NOTION_API_KEY'],
    env_configured: false,
    context_cost: 3,
    homepage: 'https://notion.so',
    mcp: {
      command: 'npx',
      args: ['-y', '@notionhq/notion-mcp-server@2.4.1'],
      env_template: { OPENAPI_MCP_HEADERS: '{"Authorization":"Bearer ${NOTION_API_KEY}"}' },
    },
  },
  {
    name: 'fetch',
    description: 'Lightweight fetch/convert URLs to markdown.',
    transport: 'stdio',
    risk: 'low',
    profiles: ['research', 'web', 'core', 'dev'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 1,
    homepage: 'https://github.com/modelcontextprotocol/servers',
    mcp: {
      command: 'npx',
      args: ['-y', 'mcp-server-fetch-typescript@0.1.1'],
    },
  },
  {
    name: 'time',
    description: 'Timezone conversion and current time tools.',
    transport: 'stdio',
    risk: 'low',
    profiles: ['utils', 'core', 'dev'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 1,
    homepage: 'https://github.com/modelcontextprotocol/servers',
    mcp: {
      command: 'npx',
      args: ['-y', '@guanxiong/mcp-server-time@1.0.0'],
    },
  },
  {
    name: 'puppeteer',
    description: 'Browser automation via Puppeteer for scraping/interaction.',
    transport: 'stdio',
    risk: 'medium',
    profiles: ['web', 'dev'],
    enabled: true,
    env_required: [],
    env_configured: true,
    context_cost: 4,
    homepage: 'https://pptr.dev',
    mcp: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-puppeteer@2025.5.12'],
    },
  },
  {
    name: 'everart',
    description: 'EverArt AI image generation tools.',
    transport: 'stdio',
    risk: 'medium',
    profiles: ['image'],
    enabled: false,
    env_required: ['EVERART_API_KEY'],
    env_configured: false,
    context_cost: 3,
    homepage: 'https://everart.ai',
    mcp: {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-everart@0.6.2'],
      env_template: { EVERART_API_KEY: '${EVERART_API_KEY}' },
    },
  },
];

export const PROFILES_LIST = ['core', 'dev', 'ops', 'data', 'web', 'research', 'code', 'content', 'image', 'email', 'cloud', 'reasoning', 'full'];
